packages:
  ansible-collections-openstack:
    specfile_path: ansible-collections-openstack.spec
    paths: [ ansible-collections-openstack ]
    files_to_sync:
      - ansible-collections-openstack.spec
    upstream_package_name: ansible-collections-openstack.cloud
    downstream_package_name: ansible-collections-openstack
    actions:
      create-archive:
        - "../get_archive.sh ./ansible-collections-openstack.spec"
  openstacksdk:
    specfile_path: python-openstacksdk.spec
    paths: [ openstacksdk ]
    files_to_sync:
      - python-openstacksdk.spec
    upstream_package_name: openstacksdk
    downstream_package_name: python-openstacksdk
    actions:
      create-archive:
        - "../get_archive.sh ./python-openstacksdk.spec"

jobs:
  - job: copr_build
    trigger: commit
    owner: lecris
    project: openstack
    targets:
      - fedora-development-x86_64
      - fedora-latest-x86_64
      - fedora-development-aarch64
      - fedora-latest-aarch64
      - epel-9-x86_64
      - epel-9-aarch64
  - job: copr_build
    trigger: pull_request
    owner: lecris
    project: openstack
    targets:
      - fedora-development-x86_64
      - fedora-latest-x86_64
      - fedora-development-aarch64
      - fedora-latest-aarch64
      - epel-9-x86_64
      - epel-9-aarch64
